return {
  {
    "rebelot/kanagawa.nvim",
    lazy = false,
    priority = 1000,
    opts = {
      theme = "dragon",
      background = { dark = "dragon" },
      colors = {
        theme = {
          dragon = {
            ui = {
              bg = "#0d0d0d",
              bg_p1 = "#1a1a1a",
              bg_p2 = "#2a2a2a",
              fg = "#c8b8a8",
              special = "#e63946",
              nontext = "#3a3a3a",
              whitespace = "#3a3a3a",
              indent = "#1a1a1a",
              float = {
                bg = "#0a0a0a",
                bg_border = "#0a0a0a",
              },
              pmenu = {
                bg = "#1a1a1a",
                bg_sel = "#e63946",
                bg_sbar = "#1a1a1a",
                bg_thumb = "#e63946",
                fg = "#c8b8a8",
                fg_sel = "#0d0d0d",
              },
            },
            syn = {
              string = "#d4956a",
              variable = "#c8b8a8",
              number = "#e8a87c",
              constant = "#e8a87c",
              identifier = "#c8b8a8",
              parameter = "#e0d0c0",
              fun = "#e63946",
              statement = "#e63946",
              keyword = "#e63946",
              operator = "#d94e6a",
              preproc = "#e0566b",
              type = "#d94e6a",
              regex = "#e8a87c",
              deprecated = "#7a7a7a",
              comment = "#5a5a5a",
              punct = "#7a7a7a",
              special1 = "#e0566b",
              special2 = "#e8a87c",
              special3 = "#d4956a",
            },
            diag = {
              error = "#ff4d5a",
              ok = "#d4956a",
              warning = "#e8a87c",
              info = "#c8b8a8",
              hint = "#7a7a7a",
            },
          },
        },
      },
      overrides = function(colors)
        return {
          Normal = { bg = "#0d0d0d", fg = "#c8b8a8" },
          NormalFloat = { bg = "#0a0a0a" },
          FloatBorder = { bg = "#0a0a0a", fg = "#e63946" },
          FloatTitle = { bg = "#0a0a0a", fg = "#e63946" },
          CursorLine = { bg = "#1a1a1a" },
          Visual = { bg = "#e63946", fg = "#0d0d0d" },
          Keyword = { fg = "#e63946" },
          String = { fg = "#d4956a" },
          Function = { fg = "#e63946" },
          Number = { fg = "#e8a87c" },
          Type = { fg = "#d94e6a" },
          Comment = { fg = "#6a6a6a", italic = true },
          LineNr = { fg = "#3a3a3a" },
          CursorLineNr = { fg = "#e63946" },
          DiagnosticError = { fg = "#ff4d5a" },
          DiagnosticWarn = { fg = "#e8a87c" },
          DiagnosticInfo = { fg = "#c8b8a8" },
          DiagnosticHint = { fg = "#7a7a7a" },
          StatusLine = { bg = "#0a0a0a", fg = "#c8b8a8" },
          StatusLineNC = { bg = "#0a0a0a", fg = "#5a5a5a" },
          TabLine = { bg = "#0a0a0a", fg = "#6a6a6a" },
          TabLineSel = { bg = "#e63946", fg = "#0d0d0d" },
          TabLineFill = { bg = "#0a0a0a" },
          WinSeparator = { fg = "#2a2a2a" },
          VertSplit = { fg = "#2a2a2a" },
          Pmenu = { bg = "#1a1a1a", fg = "#c8b8a8" },
          PmenuSel = { bg = "#e63946", fg = "#0d0d0d" },
          PmenuSbar = { bg = "#1a1a1a" },
          PmenuThumb = { bg = "#e63946" },
          Search = { bg = "#e63946", fg = "#0d0d0d" },
          IncSearch = { bg = "#ff4d5a", fg = "#0d0d0d" },
          MatchParen = { fg = "#ff4d5a", bold = true },
          Directory = { fg = "#e63946" },
          Title = { fg = "#e63946", bold = true },
          Special = { fg = "#e0566b" },
          SpecialKey = { fg = "#3a3a3a" },
          NonText = { fg = "#3a3a3a" },
          GitSignsAdd = { fg = "#d4956a" },
          GitSignsChange = { fg = "#e8a87c" },
          GitSignsDelete = { fg = "#e63946" },
          MiniStatuslineFilename = { bg = "#1a1a1a", fg = "#c8b8a8" },
          MiniStatuslineFileinfo = { bg = "#1a1a1a", fg = "#c8b8a8" },
          MiniStatuslineModeNormal = { bg = "#e63946", fg = "#0d0d0d", bold = true },
          MiniStatuslineModeInsert = { bg = "#d4956a", fg = "#0d0d0d", bold = true },
          MiniStatuslineModeVisual = { bg = "#c46b99", fg = "#0d0d0d", bold = true },
          MiniStatuslineModeReplace = { bg = "#f5e6d6", fg = "#0d0d0d", bold = true },
          MiniStatuslineModeCommand = { bg = "#e8a87c", fg = "#0d0d0d", bold = true },
          MiniTablineCurrent = { bg = "#e63946", fg = "#0d0d0d", bold = true },
          MiniTablineVisible = { bg = "#1a1a1a", fg = "#7a7a7a" },
          MiniTablineHidden = { bg = "#0a0a0a", fg = "#6a6a6a" },
          MiniTablineFill = { bg = "#0a0a0a" },
          MiniTablineModifiedCurrent = { bg = "#e63946", fg = "#0d0d0d" },
          MiniTablineModifiedVisible = { bg = "#1a1a1a", fg = "#e8a87c" },
          MiniTablineModifiedHidden = { bg = "#0a0a0a", fg = "#e8a87c" },
          TelescopeNormal = { bg = "#0a0a0a", fg = "#c8b8a8" },
          TelescopeBorder = { bg = "#0a0a0a", fg = "#e63946" },
          TelescopePromptNormal = { bg = "#1a1a1a" },
          TelescopePromptBorder = { bg = "#1a1a1a", fg = "#e63946" },
          TelescopePromptTitle = { bg = "#e63946", fg = "#0d0d0d" },
          TelescopePreviewTitle = { bg = "#e63946", fg = "#0d0d0d" },
          TelescopeResultsTitle = { bg = "#e63946", fg = "#0d0d0d" },
          TelescopeSelection = { bg = "#1a1a1a", fg = "#e0d0c0" },
          NeoTreeNormal = { bg = "#0a0a0a", fg = "#c8b8a8" },
          NeoTreeNormalNC = { bg = "#0a0a0a", fg = "#c8b8a8" },
          NeoTreeDirectoryIcon = { fg = "#e63946" },
          NeoTreeDirectoryName = { fg = "#e63946" },
          NeoTreeRootName = { fg = "#e63946", bold = true },
          NeoTreeGitModified = { fg = "#e8a87c" },
          NeoTreeGitAdded = { fg = "#d4956a" },
          NeoTreeGitDeleted = { fg = "#ff4d5a" },
          WhichKeyFloat = { bg = "#0a0a0a" },
          WhichKey = { fg = "#e63946" },
          WhichKeyGroup = { fg = "#d94e6a" },
          WhichKeyDesc = { fg = "#c8b8a8" },
          LazyButton = { bg = "#1a1a1a", fg = "#c8b8a8" },
          LazyButtonActive = { bg = "#e63946", fg = "#0d0d0d" },
          LazyH1 = { bg = "#e63946", fg = "#0d0d0d", bold = true },
        }
      end,
    },
  },
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "kanagawa-dragon",
    },
  },
}
